import { useCallback, useEffect, useState } from 'react';
import { Banknote, CheckCircle2, FileCheck2, FileText, Plus, RefreshCw, Save, Trash2, UserRound, WalletCards, XCircle } from 'lucide-react';
import { Link, Navigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../state/AuthContext';
import type { AppRole } from '../types';
import '../teacher-honor-system.css';

const MANAGEMENT_ROLES=new Set<AppRole>(['administrator','manager','co_founder','founder']);
const rupiah=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function duration(m:number){const h=Math.floor((m||0)/60),r=(m||0)%60;return h?(r?`${h} jam ${r} menit`:`${h} jam`):`${r} menit`;}
function fdate(v:string|null){if(!v)return '—';const d=new Date(`${v}T00:00:00+07:00`);return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Jakarta'}).format(d);}
const profileLabels:Record<string,string>={team_name:'Team',domicile:'Domisili',phone:'No. HP',bank_name:'Nama Bank',bank_account_name:'Nama Pemilik Rekening',bank_account_number:'Nomor Rekening',payment_method:'Metode Pembayaran',notes:'Catatan Internal'};
function payrollStatusLabel(status:Row['payroll_status']){if(status==='paid')return 'Dibayar';if(status==='finalized')return 'Final';if(status==='draft')return 'Draft';return 'Belum dibuat';}

type Row={teacher_id:string;teacher_name:string;team_name:string|null;domicile:string|null;phone:string|null;bank_name:string|null;bank_account_name:string|null;bank_account_number:string|null;payment_method:string|null;submitted_count:number;revision_count:number;approved_count:number;approved_minutes:number;payroll_id:string|null;payroll_status:'draft'|'finalized'|'paid'|null;base_amount:number|null;additions_amount:number|null;deductions_amount:number|null;net_amount:number|null;total_sessions:number|null;total_minutes:number|null;paid_on:string|null};
type Payload={month:string;period_end:string;summary:{teacher_count:number;submitted_reports:number;approved_reports:number;revision_reports:number;approved_minutes:number;generated_payrolls:number;total_net_amount:number};rows:Row[]};
type Report={report_id:string;class_id:string;class_name:string;class_code:string|null;teacher_name:string;report_date:string;starts_at:string;ends_at:string;duration_minutes:number;material_summary:string;assignment_summary:string;next_plan:string;evaluation_notes:string|null;review_status:'submitted'|'approved'|'revision';review_note:string|null;reviewed_at:string|null};
type Config={teacher:{teacher_id:string;full_name:string|null;nickname:string|null;team_name:string|null;domicile:string|null;phone:string|null;bank_name:string|null;bank_account_name:string|null;bank_account_number:string|null;payment_method:string|null;notes:string|null};classes:Array<{class_id:string;class_name:string}>;rates:Array<{rate_id:string;class_id:string|null;class_name:string|null;activity_label:string;hourly_rate:number;valid_from:string;valid_to:string|null}>};
type Payroll={payroll:{payroll_id:string;status:'draft'|'finalized'|'paid';base_amount:number;additions_amount:number;deductions_amount:number;net_amount:number;total_sessions:number;total_minutes:number;paid_on:string|null};lines:Array<{line_id:string;activity_label:string;class_name:string;report_date:string;starts_at:string;ends_at:string;duration_minutes:number;hourly_rate:number;amount:number}>;adjustments:Array<{adjustment_id:string;type:'addition'|'deduction';description:string;amount:number}>};

export function ManagementHonorPage(){
 const {role,loading:authLoading}=useAuth();const canManage=Boolean(role&&MANAGEMENT_ROLES.has(role));
 const [month,setMonth]=useState(currentMonth);const [payload,setPayload]=useState<Payload|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [selected,setSelected]=useState<Row|null>(null);const [reports,setReports]=useState<Report[]>([]);const [config,setConfig]=useState<Config|null>(null);const [payroll,setPayroll]=useState<Payroll|null>(null);const [tab,setTab]=useState<'reports'|'config'|'payroll'>('reports');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const [profile,setProfile]=useState({team_name:'Pengajar (Eduforce)',domicile:'',phone:'',bank_name:'',bank_account_name:'',bank_account_number:'',payment_method:'Transfer',notes:''});
 const [rate,setRate]=useState({rate_id:'',class_id:'',activity_label:'SEMI PRIVAT',hourly_rate:'40000',valid_from:`${month}-01`,valid_to:''});
 const [adj,setAdj]=useState({type:'addition',description:'',amount:''});
 const load=useCallback(async()=>{if(!canManage)return;setLoading(true);setError('');const {data,error:e}=await supabase.rpc('get_management_honor_overview',{p_month:`${month}-01`});if(e){console.error(e);setError('Data honor belum dapat dimuat.');}else setPayload(data as Payload);setLoading(false);},[canManage,month]);
 useEffect(()=>{if(!authLoading&&canManage)void load();},[authLoading,canManage,load]);
 async function open(row:Row,nextTab:typeof tab='reports'){setSelected(row);setTab(nextTab);setMessage('');const [a,b]=await Promise.all([supabase.rpc('get_management_teacher_month_reports',{p_teacher_id:row.teacher_id,p_month:`${month}-01`}),supabase.rpc('get_management_teacher_honor_config',{p_teacher_id:row.teacher_id})]);if(a.error||b.error){console.error(a.error||b.error);setMessage('Detail belum dapat dimuat.');return;}setReports(((a.data as {rows:Report[]})?.rows)||[]);const c=b.data as Config;setConfig(c);const t=c.teacher;setProfile({team_name:t.team_name||'Pengajar (Eduforce)',domicile:t.domicile||'',phone:t.phone||'',bank_name:t.bank_name||'',bank_account_name:t.bank_account_name||'',bank_account_number:t.bank_account_number||'',payment_method:t.payment_method||'Transfer',notes:t.notes||''});if(row.payroll_id){const p=await supabase.rpc('get_teacher_payroll_detail',{p_payroll_id:row.payroll_id});setPayroll(p.error?null:p.data as Payroll);}else setPayroll(null);}
 async function review(id:string,decision:'approved'|'revision'){const note=decision==='revision'?(window.prompt('Catatan revisi:')||''):null;if(decision==='revision'&&!note)return;setBusy(true);const {error:e}=await supabase.rpc('review_management_teaching_report',{p_report_id:id,p_decision:decision,p_note:note});setBusy(false);if(e){console.error(e);setMessage('Review gagal.');return;}if(selected){await open(selected,'reports');await load();}}
 async function saveProfile(){if(!selected)return;setBusy(true);const {error:e}=await supabase.rpc('save_management_teacher_payroll_profile',{p_teacher_id:selected.teacher_id,p_team_name:profile.team_name,p_domicile:profile.domicile,p_phone:profile.phone,p_bank_name:profile.bank_name,p_bank_account_name:profile.bank_account_name,p_bank_account_number:profile.bank_account_number,p_payment_method:profile.payment_method,p_notes:profile.notes||null});setBusy(false);if(e){console.error(e);setMessage('Profil belum tersimpan.');return;}setMessage('Profil administrasi tersimpan.');await open(selected,'config');await load();}
 async function saveRate(){if(!selected)return;setBusy(true);const {error:e}=await supabase.rpc('save_management_teacher_honor_rate',{p_teacher_id:selected.teacher_id,p_rate_id:rate.rate_id||null,p_class_id:rate.class_id||null,p_activity_label:rate.activity_label,p_hourly_rate:Number(rate.hourly_rate),p_valid_from:rate.valid_from,p_valid_to:rate.valid_to||null});setBusy(false);if(e){console.error(e);setMessage('Tarif belum tersimpan.');return;}setRate({rate_id:'',class_id:'',activity_label:'SEMI PRIVAT',hourly_rate:'40000',valid_from:`${month}-01`,valid_to:''});await open(selected,'config');}
 async function delRate(id:string){if(!selected||!window.confirm('Hapus tarif ini?'))return;await supabase.rpc('delete_management_teacher_honor_rate',{p_rate_id:id});await open(selected,'config');}
 async function generate(){if(!selected)return;setBusy(true);const {data,error:e}=await supabase.rpc('generate_management_teacher_payroll',{p_teacher_id:selected.teacher_id,p_month:`${month}-01`});setBusy(false);if(e){console.error(e);setMessage(String(e.message||'').includes('missing_honor_rate')?'Ada laporan approved yang belum mempunyai tarif sesuai kelas/tanggal.':'Rekap honor belum dapat dibuat.');return;}const p=await supabase.rpc('get_teacher_payroll_detail',{p_payroll_id:data as string});if(!p.error)setPayroll(p.data as Payroll);setTab('payroll');await load();}
 async function addAdj(){if(!payroll)return;await supabase.rpc('add_management_payroll_adjustment',{p_payroll_id:payroll.payroll.payroll_id,p_type:adj.type,p_description:adj.description,p_amount:Number(adj.amount)});setAdj({type:'addition',description:'',amount:''});if(selected){await open(selected,'payroll');await load();}}
 async function delAdj(id:string){if(!selected)return;await supabase.rpc('delete_management_payroll_adjustment',{p_adjustment_id:id});await open(selected,'payroll');await load();}
 async function finalize(){if(!payroll||!selected||!window.confirm('Finalkan honor? Data snapshot akan dikunci.'))return;await supabase.rpc('finalize_management_teacher_payroll',{p_payroll_id:payroll.payroll.payroll_id});await open(selected,'payroll');await load();}
 if(authLoading)return <div className="full-center">Memuat KOJAC LMS…</div>;if(!canManage)return <Navigate to="/" replace/>;
 const s=payload?.summary??{teacher_count:0,submitted_reports:0,approved_reports:0,revision_reports:0,approved_minutes:0,generated_payrolls:0,total_net_amount:0};
 return <div className="page honor-system-page"><header className="honor-system-header"><div><p className="eyebrow">MANAJEMEN KOJAC</p><h1><WalletCards/> Pelaporan & Honor Pengajar</h1><p>Laporan per pertemuan → approval → rekap bulanan → honor → slip.</p></div><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></header>
 <section className="honor-summary-grid"><article><FileText/><strong>{s.submitted_reports}</strong><span>Menunggu Review</span></article><article><FileCheck2/><strong>{s.approved_reports}</strong><span>Approved</span></article><article><Banknote/><strong>{duration(s.approved_minutes)}</strong><span>Durasi Approved</span></article><article><WalletCards/><strong>{rupiah.format(s.total_net_amount)}</strong><span>Total Honor</span></article></section>
 {error&&<div className="honor-notice is-error">{error}<button onClick={()=>void load()}><RefreshCw size={14}/> Coba Lagi</button></div>}
 <section className="honor-card"><div className="honor-heading"><h2>Rekap Bulanan Pengajar</h2><span>{loading?'Memuat…':`${payload?.rows.length||0} pengajar`}</span></div><div className="honor-table-wrap"><table><thead><tr><th>Pengajar</th><th>Review</th><th>Approved</th><th>Durasi</th><th>Honor</th><th>Status</th><th/></tr></thead><tbody>{payload?.rows.map(r=><tr key={r.teacher_id}><td><strong>{r.teacher_name}</strong><small>{r.team_name||'Profil honor belum lengkap'}</small></td><td>{r.submitted_count}{r.revision_count>0&&<small>{r.revision_count} revisi</small>}</td><td>{r.approved_count}</td><td>{duration(r.approved_minutes)}</td><td><strong>{r.payroll_id?rupiah.format(r.net_amount||0):'—'}</strong></td><td>{payrollStatusLabel(r.payroll_status)}</td><td><button className="honor-secondary" onClick={()=>void open(r)}><UserRound size={14}/> Kelola</button></td></tr>)}</tbody></table></div></section>
 {selected&&<div className="honor-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null);}}><aside className="honor-drawer"><header><div><p className="eyebrow">PENGAJAR</p><h2>{selected.teacher_name}</h2></div><button onClick={()=>setSelected(null)}><XCircle/></button></header><nav><button className={tab==='reports'?'active':''} onClick={()=>setTab('reports')}>Laporan</button><button className={tab==='config'?'active':''} onClick={()=>setTab('config')}>Profil & Tarif</button><button className={tab==='payroll'?'active':''} onClick={()=>setTab('payroll')}>Honor Bulanan</button></nav>{message&&<div className="honor-notice">{message}</div>}
 {tab==='reports'&&<section className="honor-section"><h3>Review Pertemuan</h3><div className="honor-report-list">{reports.map(r=><article key={r.report_id}><header><div><strong>{fdate(r.report_date)} · {r.class_name}</strong><span>{r.starts_at.slice(0,5)}–{r.ends_at.slice(0,5)} · {duration(r.duration_minutes)}</span></div><b className={`review-${r.review_status}`}>{r.review_status}</b></header><div className="report-grid"><div><span>Materi</span><p>{r.material_summary}</p></div><div><span>Tugas</span><p>{r.assignment_summary}</p></div><div><span>Rencana</span><p>{r.next_plan}</p></div><div><span>Evaluasi</span><p>{r.evaluation_notes||'—'}</p></div></div>{r.review_note&&<p className="review-note">Catatan: {r.review_note}</p>}{r.review_status!=='approved'&&<footer><button className="honor-secondary danger" disabled={busy} onClick={()=>void review(r.report_id,'revision')}><XCircle size={14}/> Revisi</button><button className="honor-primary" disabled={busy} onClick={()=>void review(r.report_id,'approved')}><CheckCircle2 size={14}/> Approve</button></footer>}</article>)}</div></section>}
 {tab==='config'&&config&&<section className="honor-section"><h3>Profil Administrasi</h3><div className="form-grid">{Object.entries(profile).map(([k,v])=><label key={k}><span>{profileLabels[k]||k}</span>{k==='notes'?<textarea value={v} onChange={e=>setProfile({...profile,[k]:e.target.value})}/>:<input value={v} onChange={e=>setProfile({...profile,[k]:e.target.value})}/>}</label>)}</div><button className="honor-primary" onClick={()=>void saveProfile()}><Save size={14}/> Simpan Profil</button><hr/><h3>Tarif Honor</h3><div className="form-grid"><label><span>Kelas</span><select value={rate.class_id} onChange={e=>setRate({...rate,class_id:e.target.value})}><option value="">Semua kelas (fallback)</option>{config.classes.map(c=><option key={c.class_id} value={c.class_id}>{c.class_name}</option>)}</select></label><label><span>Jenis kegiatan</span><input value={rate.activity_label} onChange={e=>setRate({...rate,activity_label:e.target.value})}/></label><label><span>Honor / jam</span><input type="number" value={rate.hourly_rate} onChange={e=>setRate({...rate,hourly_rate:e.target.value})}/></label><label><span>Berlaku mulai</span><input type="date" value={rate.valid_from} onChange={e=>setRate({...rate,valid_from:e.target.value})}/></label><label><span>Berlaku sampai</span><input type="date" value={rate.valid_to} onChange={e=>setRate({...rate,valid_to:e.target.value})}/></label></div><button className="honor-primary" onClick={()=>void saveRate()}><Plus size={14}/> Simpan Tarif</button><div className="rate-list">{config.rates.map(x=><div key={x.rate_id}><span><strong>{x.activity_label}</strong><small>{x.class_name||'Semua kelas'} · {fdate(x.valid_from)}{x.valid_to?` – ${fdate(x.valid_to)}`:' – seterusnya'}</small></span><strong>{rupiah.format(x.hourly_rate)}/jam</strong><button onClick={()=>setRate({rate_id:x.rate_id,class_id:x.class_id||'',activity_label:x.activity_label,hourly_rate:String(x.hourly_rate),valid_from:x.valid_from,valid_to:x.valid_to||''})}>Edit</button><button className="danger" onClick={()=>void delRate(x.rate_id)}><Trash2 size={13}/></button></div>)}</div></section>}
 {tab==='payroll'&&<section className="honor-section"><div className="honor-heading"><h3>Honor Bulanan</h3><button className="honor-primary" disabled={Boolean(payroll&&payroll.payroll.status!=='draft')} onClick={()=>void generate()}><RefreshCw size={14}/> Hitung / Refresh</button></div>{!payroll?<div className="empty">Approve laporan dan lengkapi tarif terlebih dahulu.</div>:<><div className="money-grid"><div><span>Honor Dasar</span><strong>{rupiah.format(payroll.payroll.base_amount)}</strong></div><div><span>Tambahan</span><strong>+ {rupiah.format(payroll.payroll.additions_amount)}</strong></div><div><span>Potongan</span><strong>- {rupiah.format(payroll.payroll.deductions_amount)}</strong></div><div className="net"><span>Honor Bersih</span><strong>{rupiah.format(payroll.payroll.net_amount)}</strong></div></div><div className="pay-lines">{payroll.lines.map(l=><div key={l.line_id}><span><strong>{fdate(l.report_date)} · {l.class_name}</strong><small>{l.activity_label} · {duration(l.duration_minutes)}</small></span><span>{rupiah.format(l.hourly_rate)}/jam</span><strong>{rupiah.format(l.amount)}</strong></div>)}</div>{payroll.payroll.status==='draft'&&<div className="adjust-form"><select value={adj.type} onChange={e=>setAdj({...adj,type:e.target.value})}><option value="addition">Tambahan</option><option value="deduction">Potongan</option></select><input placeholder="Keterangan" value={adj.description} onChange={e=>setAdj({...adj,description:e.target.value})}/><input type="number" placeholder="Jumlah" value={adj.amount} onChange={e=>setAdj({...adj,amount:e.target.value})}/><button className="honor-secondary" onClick={()=>void addAdj()}><Plus size={14}/> Tambah</button></div>}<div className="adjust-list">{payroll.adjustments.map(a=><div key={a.adjustment_id}><span>{a.type==='addition'?'+':'−'} {a.description}</span><strong>{rupiah.format(a.amount)}</strong>{payroll.payroll.status==='draft'&&<button onClick={()=>void delAdj(a.adjustment_id)}><Trash2 size={13}/></button>}</div>)}</div><footer className="pay-actions"><Link className="honor-secondary" target="_blank" to={`/honor/slip/${payroll.payroll.payroll_id}`}><FileText size={14}/> Preview Slip</Link>{payroll.payroll.status==='draft'&&<button className="honor-primary" onClick={()=>void finalize()}>Finalkan</button>}{payroll.payroll.status==='finalized'&&<Link className="honor-primary" to="/manajemen/pembayaran-honor">Buka Pembayaran Honor</Link>}{payroll.payroll.status==='paid'&&<strong>Dibayar {fdate(payroll.payroll.paid_on)}</strong>}</footer></>}</section>}
 </aside></div>}
 </div>;
}
