export type GrammarExerciseType =
  | 'multiple_choice'
  | 'pattern_choice'
  | 'fill_blank'
  | 'conjugation'
  | 'sentence_order'
  | 'error_correction';

export interface GrammarExercise {
  id: string;
  patternId: string;
  type: GrammarExerciseType;
  instruction: string;
  prompt: string;
  context?: string;
  reading?: string;
  audioText?: string;
  options?: string[];
  answer: string;
  acceptableAnswers?: string[];
  tokens?: string[];
  resultSentence?: string;
  transformationSteps?: string[];
  hint?: string;
  explanation: string;
}

export const GRAMMAR_EXERCISES: GrammarExercise[] = [
  // Bab 1 · ～は～です
  {
    id: 'ex-ch1-desu-01',
    patternId: 'ch1-desu',
    type: 'multiple_choice',
    instruction: 'Pilih partikel yang benar.',
    prompt: 'わたし（　）学生です。',
    reading: 'わたし（　）がくせいです。',
    audioText: 'わたしは学生です。',
    options: ['は', 'を', 'で', 'に'],
    answer: 'は',
    hint: 'Perhatikan partikel yang menandai topik kalimat.',
    explanation: 'は menandai topik yang sedang dibicarakan. Dalam pola dasar ini, わたし adalah topik dan 学生です adalah informasi tentang topik tersebut.',
    resultSentence: 'わたしは学生です。',
  },
  {
    id: 'ex-ch1-desu-02',
    patternId: 'ch1-desu',
    type: 'fill_blank',
    instruction: 'Lengkapi kalimat sesuai arti.',
    prompt: '田中さんは ________。',
    context: 'Tanaka adalah guru.',
    reading: 'たなかさんは ________。',
    options: ['先生です', '先生ですか', '先生ではありません', '先生をです'],
    answer: '先生です',
    hint: 'Gunakan bentuk nominal positif yang sopan.',
    explanation: 'Untuk menyatakan “A adalah B” secara sopan, gunakan A は B です.',
    resultSentence: '田中さんは先生です。',
  },
  {
    id: 'ex-ch1-desu-03',
    patternId: 'ch1-desu',
    type: 'sentence_order',
    instruction: 'Susun potongan menjadi kalimat yang benar.',
    prompt: 'Saya adalah orang Indonesia.',
    tokens: ['インドネシア人', 'です。', '私は'],
    answer: '私はインドネシア人です。',
    hint: 'Urutan dasarnya: topik + は + predikat nominal + です.',
    explanation: '私は menjadi topik, lalu インドネシア人です menjadi informasi tentang topik tersebut.',
    resultSentence: '私はインドネシア人です。',
  },
  {
    id: 'ex-ch1-desu-04',
    patternId: 'ch1-desu',
    type: 'error_correction',
    instruction: 'Pilih perbaikan yang benar.',
    prompt: 'SALAH: 私は学生はです。',
    options: ['私は学生です。', '私はは学生です。', '私を学生です。', '私は学生で。'],
    answer: '私は学生です。',
    hint: 'は cukup menandai topik; jangan menambah は di depan です.',
    explanation: 'Dalam A は B です, は ditempatkan setelah topik A. Predikat nominal B langsung diikuti です.',
    resultSentence: '私は学生です。',
  },
  {
    id: 'ex-ch1-desu-05',
    patternId: 'ch1-desu',
    type: 'multiple_choice',
    instruction: 'Pilih kalimat Jepang yang sesuai.',
    prompt: 'Ayah saya adalah karyawan perusahaan.',
    options: ['父は会社員です。', '父を会社員です。', '父は会社員ですか。', '父も会社員ではありません。'],
    answer: '父は会社員です。',
    reading: 'ちちは かいしゃいんです。',
    audioText: '父は会社員です。',
    hint: 'Kalimat ini adalah pernyataan positif, bukan pertanyaan atau negatif.',
    explanation: 'Pernyataan identitas/pekerjaan menggunakan pola KB1 は KB2 です.',
  },

  // Bab 1 · ～も
  {
    id: 'ex-ch1-mo-01',
    patternId: 'ch1-mo',
    type: 'multiple_choice',
    instruction: 'Pilih partikel yang paling tepat sesuai konteks.',
    prompt: '私は学生です。山田さん（　）学生です。',
    context: 'Saya pelajar. Yamada juga pelajar.',
    options: ['も', 'は', 'を', 'に'],
    answer: 'も',
    hint: 'Kata kunci konteksnya adalah “juga”.',
    explanation: 'も digunakan untuk menyatakan bahwa informasi tentang Yamada sama dengan informasi sebelumnya, yaitu sama-sama pelajar.',
    resultSentence: '私は学生です。山田さんも学生です。',
  },
  {
    id: 'ex-ch1-mo-02',
    patternId: 'ch1-mo',
    type: 'fill_blank',
    instruction: 'Lengkapi kalimat kedua.',
    prompt: '父は会社員です。母も ________。',
    context: 'Ayah saya karyawan perusahaan. Ibu saya juga karyawan perusahaan.',
    options: ['会社員です', '会社員ですか', '会社員をです', '会社員ではありません'],
    answer: '会社員です',
    hint: 'Informasi pada kalimat kedua sama dengan kalimat pertama.',
    explanation: 'も menggantikan は untuk menyatakan “juga”, sedangkan predikat nominal tetap memakai です.',
    resultSentence: '父は会社員です。母も会社員です。',
  },
  {
    id: 'ex-ch1-mo-03',
    patternId: 'ch1-mo',
    type: 'sentence_order',
    instruction: 'Susun menjadi kalimat yang benar.',
    prompt: 'Adik perempuan saya juga pelajar.',
    tokens: ['学生', '妹も', 'です。'],
    answer: '妹も学生です。',
    hint: 'Letakkan も setelah topik yang berarti “juga”.',
    explanation: '妹も menunjukkan “adik perempuan saya juga”, kemudian 学生です menyatakan statusnya.',
    resultSentence: '妹も学生です。',
  },
  {
    id: 'ex-ch1-mo-04',
    patternId: 'ch1-mo',
    type: 'error_correction',
    instruction: 'Pilih perbaikan yang benar.',
    prompt: 'SALAH: 私も学生はです。',
    options: ['私も学生です。', '私はも学生です。', '私もは学生です。', '私を学生もです。'],
    answer: '私も学生です。',
    hint: 'も sudah berfungsi sebagai penanda topik “juga”.',
    explanation: 'Dalam pola ini, も menggantikan は. Setelah 学生 langsung gunakan です.',
    resultSentence: '私も学生です。',
  },
  {
    id: 'ex-ch1-mo-05',
    patternId: 'ch1-mo',
    type: 'multiple_choice',
    instruction: 'Pilih kalimat yang berarti “Saya juga pelajar.”',
    prompt: 'Saya juga pelajar.',
    options: ['私も学生です。', '私は学生です。', '私の学生です。', '私を学生です。'],
    answer: '私も学生です。',
    reading: 'わたしも がくせいです。',
    audioText: '私も学生です。',
    hint: 'Cari partikel yang berarti “juga / pun”.',
    explanation: 'も menyatakan bahwa pembicara mempunyai status yang sama dengan orang yang disebut sebelumnya.',
  },

  // Bab 1 · の
  {
    id: 'ex-ch1-no-01',
    patternId: 'ch1-no',
    type: 'multiple_choice',
    instruction: 'Pilih partikel yang benar.',
    prompt: 'これは私（　）本です。',
    reading: 'これは わたし（　）ほんです。',
    options: ['の', 'も', 'は', 'で'],
    answer: 'の',
    hint: 'Hubungkan “saya” dan “buku” untuk menunjukkan kepemilikan.',
    explanation: 'の menghubungkan dua kata benda. 私の本 berarti “buku saya”.',
    resultSentence: 'これは私の本です。',
  },
  {
    id: 'ex-ch1-no-02',
    patternId: 'ch1-no',
    type: 'fill_blank',
    instruction: 'Lengkapi sesuai arti.',
    prompt: 'それは ________。',
    context: 'Itu adalah kamus bahasa Jepang.',
    options: ['日本語の辞書です', '日本語を辞書です', '日本語も辞書です', '日本語辞書のです'],
    answer: '日本語の辞書です',
    hint: 'Gunakan の untuk menghubungkan jenis bahasa dan benda.',
    explanation: '日本語の辞書 berarti “kamus bahasa Jepang”. の dapat menunjukkan jenis atau kategori, bukan hanya kepemilikan.',
    resultSentence: 'それは日本語の辞書です。',
  },
  {
    id: 'ex-ch1-no-03',
    patternId: 'ch1-no',
    type: 'sentence_order',
    instruction: 'Susun menjadi kalimat yang benar.',
    prompt: 'Tanaka adalah karyawan perusahaan Jepang.',
    tokens: ['日本の', '会社員です。', '田中さんは'],
    answer: '田中さんは日本の会社員です。',
    hint: '日本 menjelaskan 会社員 melalui の.',
    explanation: '日本の会社員 membentuk frasa “karyawan perusahaan Jepang / karyawan Jepang” dalam pola pembelajaran ini.',
    resultSentence: '田中さんは日本の会社員です。',
  },
  {
    id: 'ex-ch1-no-04',
    patternId: 'ch1-no',
    type: 'error_correction',
    instruction: 'Pilih perbaikan yang benar.',
    prompt: 'SALAH: これは私本です。',
    options: ['これは私の本です。', 'これは私を本です。', 'これは私も本です。', 'これは私本のです。'],
    answer: 'これは私の本です。',
    hint: 'Dua kata benda perlu dihubungkan.',
    explanation: '私 dan 本 harus dihubungkan dengan の untuk menyatakan “buku saya”.',
    resultSentence: 'これは私の本です。',
  },
  {
    id: 'ex-ch1-no-05',
    patternId: 'ch1-no',
    type: 'multiple_choice',
    instruction: 'Pilih kalimat yang sesuai arti.',
    prompt: 'Ini adalah tas guru.',
    options: ['これは先生のかばんです。', 'これは先生をかばんです。', 'これは先生もかばんです。', 'これは先生かばんのです。'],
    answer: 'これは先生のかばんです。',
    reading: 'これは せんせいの かばんです。',
    audioText: 'これは先生のかばんです。',
    hint: '“Tas guru” adalah hubungan kepemilikan/atribut antara dua kata benda.',
    explanation: '先生のかばん berarti “tas milik guru”.',
  },

  // Bab 6 · Tempat + で + KK
  {
    id: 'ex-ch6-place-de-01',
    patternId: 'ch6-place-de',
    type: 'multiple_choice',
    instruction: 'Pilih partikel tempat kegiatan yang benar.',
    prompt: '図書館（　）本を読みます。',
    reading: 'としょかん（　）ほんを よみます。',
    options: ['で', 'に', 'へ', 'を'],
    answer: 'で',
    hint: 'Membaca adalah kegiatan yang berlangsung di suatu tempat.',
    explanation: 'で menandai tempat berlangsungnya tindakan. 図書館で本を読みます berarti “membaca buku di perpustakaan”.',
    resultSentence: '図書館で本を読みます。',
  },
  {
    id: 'ex-ch6-place-de-02',
    patternId: 'ch6-place-de',
    type: 'multiple_choice',
    instruction: 'Pilih partikel yang benar berdasarkan fungsi tempat.',
    prompt: '学校（　）日本語を勉強します。',
    context: 'Saya belajar bahasa Jepang di sekolah.',
    options: ['で', 'に', 'へ', 'の'],
    answer: 'で',
    hint: 'Sekolah adalah lokasi berlangsungnya kegiatan belajar, bukan tujuan perpindahan.',
    explanation: 'Karena 勉強します adalah kegiatan, lokasi kegiatan ditandai dengan で.',
    resultSentence: '学校で日本語を勉強します。',
  },
  {
    id: 'ex-ch6-place-de-03',
    patternId: 'ch6-place-de',
    type: 'fill_blank',
    instruction: 'Lengkapi kalimat sesuai konteks.',
    prompt: 'レストランで ________。',
    context: 'Saya makan siang di restoran.',
    options: ['昼ご飯を食べます', '昼ご飯に食べます', '昼ご飯で食べます', '昼ご飯へ食べます'],
    answer: '昼ご飯を食べます',
    hint: 'で sudah menandai tempat; objek yang dimakan ditandai を.',
    explanation: 'レストランで menandai lokasi kegiatan, sedangkan 昼ご飯を menandai objek dari 食べます.',
    resultSentence: 'レストランで昼ご飯を食べます。',
  },
  {
    id: 'ex-ch6-place-de-04',
    patternId: 'ch6-place-de',
    type: 'sentence_order',
    instruction: 'Susun menjadi kalimat yang benar.',
    prompt: 'Saya berbicara dengan teman di taman.',
    tokens: ['友達と', '話します。', '公園で'],
    answer: '公園で友達と話します。',
    hint: 'Letakkan tempat kegiatan + で sebelum bagian kegiatan.',
    explanation: '公園で menunjukkan lokasi kegiatan, 友達と menunjukkan teman beraktivitas, dan 話します adalah kegiatannya.',
    resultSentence: '公園で友達と話します。',
  },
  {
    id: 'ex-ch6-place-de-05',
    patternId: 'ch6-place-de',
    type: 'error_correction',
    instruction: 'Pilih perbaikan yang benar.',
    prompt: 'SALAH: 私は図書館に本を読みます。',
    options: ['私は図書館で本を読みます。', '私は図書館へ本を読みます。', '私は図書館を本で読みます。', '私は図書館の本をで読みます。'],
    answer: '私は図書館で本を読みます。',
    hint: 'Yang ingin ditandai adalah tempat berlangsungnya kegiatan membaca.',
    explanation: 'Tempat berlangsungnya kegiatan ditandai で. に mempunyai fungsi lain seperti tujuan keberadaan atau waktu tertentu.',
    resultSentence: '私は図書館で本を読みます。',
  },

  // Bab 13 · ～たいです
  {
    id: 'ex-ch13-tai-01',
    patternId: 'ch13-tai',
    type: 'conjugation',
    instruction: 'Ubah ke bentuk ～たいです.',
    prompt: '行きます → ?',
    options: ['行きたいです', '行くたいです', '行きますたいです', '行ってたいです'],
    answer: '行きたいです',
    hint: 'Gunakan stem bentuk ます.',
    explanation: '行きます → hilangkan ます → 行き → tambahkan たいです → 行きたいです.',
    transformationSteps: ['行きます', '行き', '行きたいです'],
  },
  {
    id: 'ex-ch13-tai-02',
    patternId: 'ch13-tai',
    type: 'multiple_choice',
    instruction: 'Pilih pola yang sesuai arti.',
    prompt: '寿司を ________。',
    context: 'Saya ingin makan sushi.',
    options: ['食べたいです', '食べています', '食べましたか', '食べてください'],
    answer: '食べたいです',
    hint: 'Pola target menyatakan keinginan pembicara.',
    explanation: '食べます → 食べ + たいです = 食べたいです.',
    resultSentence: '寿司を食べたいです。',
  },
  {
    id: 'ex-ch13-tai-03',
    patternId: 'ch13-tai',
    type: 'fill_blank',
    instruction: 'Lengkapi sesuai konteks.',
    prompt: '週末、ゆっくり ________。',
    context: 'Akhir pekan saya ingin beristirahat dengan santai.',
    options: ['休みたいです', '休むたいです', '休んでください', '休みましたか'],
    answer: '休みたいです',
    hint: '休みます memiliki stem 休み.',
    explanation: '休みます → 休み → 休みたいです.',
    resultSentence: '週末、ゆっくり休みたいです。',
  },
  {
    id: 'ex-ch13-tai-04',
    patternId: 'ch13-tai',
    type: 'sentence_order',
    instruction: 'Susun menjadi kalimat yang benar.',
    prompt: 'Saya ingin pergi ke Jepang.',
    tokens: ['日本へ', '行きたいです。', '私は'],
    answer: '私は日本へ行きたいです。',
    hint: 'Topik dapat diletakkan di awal, lalu tujuan dan keinginan.',
    explanation: '私は adalah topik, 日本へ adalah tujuan, dan 行きたいです menyatakan keinginan melakukan tindakan.',
    resultSentence: '私は日本へ行きたいです。',
  },
  {
    id: 'ex-ch13-tai-05',
    patternId: 'ch13-tai',
    type: 'error_correction',
    instruction: 'Pilih perbaikan yang benar.',
    prompt: 'SALAH: 私は日本へ行くたいです。',
    options: ['私は日本へ行きたいです。', '私は日本へ行ってたいです。', '私は日本へ行きますたいです。', '私は日本へ行くですたい。'],
    answer: '私は日本へ行きたいです。',
    hint: '～たい ditempelkan pada stem bentuk ます, bukan bentuk kamus.',
    explanation: '行きます → 行き → 行きたいです. Karena itu 行くたいです tidak benar.',
    transformationSteps: ['行きます', '行き', '行きたいです'],
    resultSentence: '私は日本へ行きたいです。',
  },

  // Bab 15 · ～てもいいです
  {
    id: 'ex-ch15-temoii-01',
    patternId: 'ch15-temoii',
    type: 'multiple_choice',
    instruction: 'Pilih pola yang tepat.',
    prompt: '写真を撮って ________。',
    context: 'Bolehkah saya mengambil foto?',
    options: ['もいいですか', 'はいけません', 'ください', 'います'],
    answer: 'もいいですか',
    hint: 'Gunakan pola untuk meminta izin.',
    explanation: 'KK bentuk て + もいいですか digunakan untuk menanyakan apakah suatu tindakan diperbolehkan.',
    resultSentence: '写真を撮ってもいいですか。',
  },
  {
    id: 'ex-ch15-temoii-02',
    patternId: 'ch15-temoii',
    type: 'fill_blank',
    instruction: 'Lengkapi kalimat.',
    prompt: 'ここに座って ________。',
    context: 'Boleh duduk di sini.',
    options: ['もいいです', 'はいけません', 'くださいません', 'いますか'],
    answer: 'もいいです',
    hint: 'Kalimat ini memberi izin, bukan melarang.',
    explanation: '座って + もいいです menyatakan bahwa tindakan duduk diperbolehkan.',
    resultSentence: 'ここに座ってもいいです。',
  },
  {
    id: 'ex-ch15-temoii-03',
    patternId: 'ch15-temoii',
    type: 'sentence_order',
    instruction: 'Susun menjadi kalimat permintaan izin yang benar.',
    prompt: 'Bolehkah saya menggunakan pena ini?',
    tokens: ['使っても', 'このペンを', 'いいですか。'],
    answer: 'このペンを使ってもいいですか。',
    hint: 'Objek + KK bentuk て + もいいですか.',
    explanation: 'このペンを adalah objek, kemudian 使ってもいいですか meminta izin untuk menggunakannya.',
    resultSentence: 'このペンを使ってもいいですか。',
  },
  {
    id: 'ex-ch15-temoii-04',
    patternId: 'ch15-temoii',
    type: 'error_correction',
    instruction: 'Pilih perbaikan yang benar.',
    prompt: 'SALAH: 写真を撮るてもいいですか。',
    options: ['写真を撮ってもいいですか。', '写真を撮りてもいいですか。', '写真を撮るもいいですか。', '写真を撮ってはいけませんか。'],
    answer: '写真を撮ってもいいですか。',
    hint: 'Sebelum もいいです gunakan bentuk て.',
    explanation: '撮る berubah menjadi 撮って dalam bentuk て, lalu diikuti もいいですか.',
    transformationSteps: ['撮る', '撮って', '撮ってもいいですか'],
    resultSentence: '写真を撮ってもいいですか。',
  },
  {
    id: 'ex-ch15-temoii-05',
    patternId: 'ch15-temoii',
    type: 'multiple_choice',
    instruction: 'Pilih kalimat yang sesuai arti.',
    prompt: 'Hari ini boleh pulang lebih awal.',
    options: ['今日は早く帰ってもいいです。', '今日は早く帰ってはいけません。', '今日は早く帰りたいですか。', '今日は早く帰ってくださいか。'],
    answer: '今日は早く帰ってもいいです。',
    reading: 'きょうは はやく かえっても いいです。',
    audioText: '今日は早く帰ってもいいです。',
    hint: 'Cari pola yang menyatakan izin.',
    explanation: '帰ってもいいです berarti tindakan pulang diperbolehkan.',
  },

  // Bab 15 · ～てはいけません
  {
    id: 'ex-ch15-tewaikenai-01',
    patternId: 'ch15-tewaikenai',
    type: 'multiple_choice',
    instruction: 'Pilih pola yang tepat.',
    prompt: 'ここでたばこを吸って ________。',
    context: 'Tidak boleh merokok di sini.',
    options: ['はいけません', 'もいいです', 'ください', 'います'],
    answer: 'はいけません',
    hint: 'Kalimat ini adalah larangan.',
    explanation: 'KK bentuk て + はいけません digunakan untuk menyatakan bahwa tindakan tersebut tidak diperbolehkan.',
    resultSentence: 'ここでたばこを吸ってはいけません。',
  },
  {
    id: 'ex-ch15-tewaikenai-02',
    patternId: 'ch15-tewaikenai',
    type: 'fill_blank',
    instruction: 'Lengkapi kalimat larangan.',
    prompt: 'この部屋に入って ________。',
    context: 'Tidak boleh masuk ruangan ini.',
    options: ['はいけません', 'もいいです', 'ください', 'みたいです'],
    answer: 'はいけません',
    hint: 'Gunakan pasangan pola larangan dari ～てもいいです.',
    explanation: '入ってはいけません berarti “tidak boleh masuk”.',
    resultSentence: 'この部屋に入ってはいけません。',
  },
  {
    id: 'ex-ch15-tewaikenai-03',
    patternId: 'ch15-tewaikenai',
    type: 'sentence_order',
    instruction: 'Susun menjadi kalimat larangan yang benar.',
    prompt: 'Tidak boleh memarkir mobil di sini.',
    tokens: ['車を', 'ここに', '止めてはいけません。'],
    answer: 'ここに車を止めてはいけません。',
    hint: 'Tempat + objek + tindakan larangan.',
    explanation: 'ここに menunjukkan lokasi, 車を adalah objek, dan 止めてはいけません menyatakan larangan.',
    resultSentence: 'ここに車を止めてはいけません。',
  },
  {
    id: 'ex-ch15-tewaikenai-04',
    patternId: 'ch15-tewaikenai',
    type: 'error_correction',
    instruction: 'Pilih perbaikan yang benar.',
    prompt: 'SALAH: ここでたばこを吸うてはいけません。',
    options: ['ここでたばこを吸ってはいけません。', 'ここでたばこを吸いてはいけません。', 'ここでたばこを吸うはいけません。', 'ここでたばこを吸ってもいいです。'],
    answer: 'ここでたばこを吸ってはいけません。',
    hint: '吸う adalah verba kelompok 1 dengan bentuk て 吸って.',
    explanation: '吸う → 吸って. Setelah itu tambahkan はいけません untuk menyatakan larangan.',
    transformationSteps: ['吸う', '吸って', '吸ってはいけません'],
    resultSentence: 'ここでたばこを吸ってはいけません。',
  },
  {
    id: 'ex-ch15-tewaikenai-05',
    patternId: 'ch15-tewaikenai',
    type: 'multiple_choice',
    instruction: 'Pilih kalimat yang sesuai arti.',
    prompt: 'Tidak boleh menggunakan telepon selama pelajaran.',
    options: ['授業中に電話を使ってはいけません。', '授業中に電話を使ってもいいです。', '授業中に電話を使いたいです。', '授業中に電話を使ってください。'],
    answer: '授業中に電話を使ってはいけません。',
    reading: 'じゅぎょうちゅうに でんわを つかってはいけません。',
    audioText: '授業中に電話を使ってはいけません。',
    hint: 'Cari pola larangan, bukan izin atau permintaan.',
    explanation: '使ってはいけません menyatakan bahwa penggunaan telepon tidak diperbolehkan.',
  },

  // Bab 19 · ～たことがあります
  {
    id: 'ex-ch19-ta-koto-01',
    patternId: 'ch19-ta-koto-ga-aru',
    type: 'fill_blank',
    instruction: 'Lengkapi kalimat pengalaman.',
    prompt: '日本へ ________。',
    context: 'Saya pernah pergi ke Jepang.',
    options: ['行ったことがあります', '行くことがあります', '行きたいです', '行っています'],
    answer: '行ったことがあります',
    hint: 'Pengalaman memakai bentuk た + ことがあります.',
    explanation: '行く → bentuk た adalah 行った → 行ったことがあります.',
    transformationSteps: ['行く', '行った', '行ったことがあります'],
    resultSentence: '日本へ行ったことがあります。',
  },
  {
    id: 'ex-ch19-ta-koto-02',
    patternId: 'ch19-ta-koto-ga-aru',
    type: 'multiple_choice',
    instruction: 'Pilih kalimat yang sesuai arti.',
    prompt: 'Saya pernah naik Shinkansen.',
    options: ['新幹線に乗ったことがあります。', '新幹線に乗ることがあります。', '新幹線に乗りたいです。', '新幹線に乗っています。'],
    answer: '新幹線に乗ったことがあります。',
    reading: 'しんかんせんに のったことが あります。',
    audioText: '新幹線に乗ったことがあります。',
    hint: 'Cari bentuk lampau + ことがあります.',
    explanation: '乗る → 乗った. Bentuk 乗ったことがあります menyatakan pengalaman pernah naik.',
  },
  {
    id: 'ex-ch19-ta-koto-03',
    patternId: 'ch19-ta-koto-ga-aru',
    type: 'sentence_order',
    instruction: 'Susun menjadi kalimat pengalaman yang benar.',
    prompt: 'Saya pernah mendaki Gunung Fuji.',
    tokens: ['あります。', '富士山に', '登ったことが'],
    answer: '富士山に登ったことがあります。',
    hint: 'Tujuan/tempat + bentuk た + ことがあります.',
    explanation: '登った adalah bentuk た dari 登る. Pola lengkapnya menjadi 登ったことがあります.',
    resultSentence: '富士山に登ったことがあります。',
  },
  {
    id: 'ex-ch19-ta-koto-04',
    patternId: 'ch19-ta-koto-ga-aru',
    type: 'error_correction',
    instruction: 'Pilih perbaikan sesuai arti “Saya pernah pergi ke Jepang.”',
    prompt: 'SALAH UNTUK MAKNA INI: 日本へ行くことがあります。',
    options: ['日本へ行ったことがあります。', '日本へ行くことがあります。', '日本へ行きたいことがあります。', '日本へ行ってことがあります。'],
    answer: '日本へ行ったことがあります。',
    hint: '行くことがあります berarti “kadang-kadang pergi”, bukan pengalaman “pernah”.',
    explanation: 'Untuk pengalaman masa lalu gunakan bentuk た: 行く → 行った → 行ったことがあります.',
    transformationSteps: ['行く', '行った', '行ったことがあります'],
    resultSentence: '日本へ行ったことがあります。',
  },
  {
    id: 'ex-ch19-ta-koto-05',
    patternId: 'ch19-ta-koto-ga-aru',
    type: 'conjugation',
    instruction: 'Ubah ke pola pengalaman ～たことがあります.',
    prompt: '食べます → ?',
    options: ['食べたことがあります', '食べることがあります', '食べてことがあります', '食べたいことがあります'],
    answer: '食べたことがあります',
    hint: 'Ubah 食べる menjadi bentuk た terlebih dahulu.',
    explanation: '食べる → 食べた → 食べたことがあります.',
    transformationSteps: ['食べる', '食べた', '食べたことがあります'],
  },
];

export function getGrammarExercises(patternId: string) {
  return GRAMMAR_EXERCISES.filter((exercise) => exercise.patternId === patternId);
}

export function getGrammarPracticePatternIds() {
  return [...new Set(GRAMMAR_EXERCISES.map((exercise) => exercise.patternId))];
}
