-- KOJAC LMS — Phase Kanji 1
-- Migration 010: curated Kanji N5 starter dataset (90 kanji)
-- Incremental only. Does not alter Hiragana, Katakana, Vocabulary, review_progress, or RLS.
-- This is a practical KOJAC teaching set; it is not presented as an official immutable JLPT list.

insert into public.learning_items as li (
  item_type,
  jlpt_level,
  prompt,
  reading,
  meaning_id,
  meaning_en,
  extra,
  is_published
)
values
  ('kanji','N5','一',null,'satu',null,'{"sort_order":1,"category":"Angka","onyomi":["イチ","イツ"],"kunyomi":["ひと.つ"],"stroke_count":1,"examples":[{"word":"一つ","reading":"ひとつ","romaji":"hitotsu","meaning_id":"satu buah / satu benda"},{"word":"一人","reading":"ひとり","romaji":"hitori","meaning_id":"satu orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','二',null,'dua',null,'{"sort_order":2,"category":"Angka","onyomi":["ニ"],"kunyomi":["ふた.つ"],"stroke_count":2,"examples":[{"word":"二つ","reading":"ふたつ","romaji":"futatsu","meaning_id":"dua buah / dua benda"},{"word":"二人","reading":"ふたり","romaji":"futari","meaning_id":"dua orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','三',null,'tiga',null,'{"sort_order":3,"category":"Angka","onyomi":["サン"],"kunyomi":["みっ.つ"],"stroke_count":3,"examples":[{"word":"三つ","reading":"みっつ","romaji":"mittsu","meaning_id":"tiga buah / tiga benda"},{"word":"三人","reading":"さんにん","romaji":"sannin","meaning_id":"tiga orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','四',null,'empat',null,'{"sort_order":4,"category":"Angka","onyomi":["シ"],"kunyomi":["よん","よ.つ","よっ.つ"],"stroke_count":5,"examples":[{"word":"四つ","reading":"よっつ","romaji":"yottsu","meaning_id":"empat buah / empat benda"},{"word":"四人","reading":"よにん","romaji":"yonin","meaning_id":"empat orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','五',null,'lima',null,'{"sort_order":5,"category":"Angka","onyomi":["ゴ"],"kunyomi":["いつ.つ"],"stroke_count":4,"examples":[{"word":"五つ","reading":"いつつ","romaji":"itsutsu","meaning_id":"lima buah / lima benda"},{"word":"五人","reading":"ごにん","romaji":"gonin","meaning_id":"lima orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','六',null,'enam',null,'{"sort_order":6,"category":"Angka","onyomi":["ロク"],"kunyomi":["むっ.つ"],"stroke_count":4,"examples":[{"word":"六つ","reading":"むっつ","romaji":"muttsu","meaning_id":"enam buah / enam benda"},{"word":"六人","reading":"ろくにん","romaji":"rokunin","meaning_id":"enam orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','七',null,'tujuh',null,'{"sort_order":7,"category":"Angka","onyomi":["シチ"],"kunyomi":["なな","なな.つ"],"stroke_count":2,"examples":[{"word":"七つ","reading":"ななつ","romaji":"nanatsu","meaning_id":"tujuh buah / tujuh benda"},{"word":"七人","reading":"しちにん","romaji":"shichinin","meaning_id":"tujuh orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','八',null,'delapan',null,'{"sort_order":8,"category":"Angka","onyomi":["ハチ"],"kunyomi":["やっ.つ"],"stroke_count":2,"examples":[{"word":"八つ","reading":"やっつ","romaji":"yattsu","meaning_id":"delapan buah / delapan benda"},{"word":"八人","reading":"はちにん","romaji":"hachinin","meaning_id":"delapan orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','九',null,'sembilan',null,'{"sort_order":9,"category":"Angka","onyomi":["キュウ","ク"],"kunyomi":["ここの.つ"],"stroke_count":2,"examples":[{"word":"九つ","reading":"ここのつ","romaji":"kokonotsu","meaning_id":"sembilan buah / sembilan benda"},{"word":"九人","reading":"きゅうにん","romaji":"kyuunin","meaning_id":"sembilan orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','十',null,'sepuluh',null,'{"sort_order":10,"category":"Angka","onyomi":["ジュウ"],"kunyomi":["とお"],"stroke_count":2,"examples":[{"word":"十","reading":"とお","romaji":"too","meaning_id":"sepuluh"},{"word":"十人","reading":"じゅうにん","romaji":"juunin","meaning_id":"sepuluh orang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','百',null,'seratus',null,'{"sort_order":11,"category":"Angka","onyomi":["ヒャク"],"kunyomi":[],"stroke_count":6,"examples":[{"word":"百円","reading":"ひゃくえん","romaji":"hyaku en","meaning_id":"seratus yen"},{"word":"三百円","reading":"さんびゃくえん","romaji":"sanbyaku en","meaning_id":"tiga ratus yen"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','千',null,'seribu',null,'{"sort_order":12,"category":"Angka","onyomi":["セン"],"kunyomi":[],"stroke_count":3,"examples":[{"word":"千円","reading":"せんえん","romaji":"sen en","meaning_id":"seribu yen"},{"word":"三千円","reading":"さんぜんえん","romaji":"sanzen en","meaning_id":"tiga ribu yen"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','万',null,'sepuluh ribu',null,'{"sort_order":13,"category":"Angka","onyomi":["マン","バン"],"kunyomi":[],"stroke_count":3,"examples":[{"word":"一万","reading":"いちまん","romaji":"ichiman","meaning_id":"sepuluh ribu"},{"word":"一万円","reading":"いちまんえん","romaji":"ichiman en","meaning_id":"sepuluh ribu yen"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','円',null,'yen / lingkaran',null,'{"sort_order":14,"category":"Angka","onyomi":["エン"],"kunyomi":[],"stroke_count":4,"examples":[{"word":"円","reading":"えん","romaji":"en","meaning_id":"yen"},{"word":"百円","reading":"ひゃくえん","romaji":"hyaku en","meaning_id":"seratus yen"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','日',null,'hari / matahari',null,'{"sort_order":15,"category":"Waktu","onyomi":["ニチ","ジツ"],"kunyomi":["ひ","か"],"stroke_count":4,"examples":[{"word":"日本","reading":"にほん","romaji":"nihon","meaning_id":"Jepang"},{"word":"日曜日","reading":"にちようび","romaji":"nichiyoubi","meaning_id":"hari Minggu"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','月',null,'bulan / bulan di langit',null,'{"sort_order":16,"category":"Waktu","onyomi":["ゲツ","ガツ"],"kunyomi":["つき"],"stroke_count":4,"examples":[{"word":"月曜日","reading":"げつようび","romaji":"getsuyoubi","meaning_id":"hari Senin"},{"word":"今月","reading":"こんげつ","romaji":"kongetsu","meaning_id":"bulan ini"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','火',null,'api',null,'{"sort_order":17,"category":"Alam","onyomi":["カ"],"kunyomi":["ひ"],"stroke_count":4,"examples":[{"word":"火","reading":"ひ","romaji":"hi","meaning_id":"api"},{"word":"火曜日","reading":"かようび","romaji":"kayoubi","meaning_id":"hari Selasa"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','水',null,'air',null,'{"sort_order":18,"category":"Alam","onyomi":["スイ"],"kunyomi":["みず"],"stroke_count":4,"examples":[{"word":"水","reading":"みず","romaji":"mizu","meaning_id":"air"},{"word":"水曜日","reading":"すいようび","romaji":"suiyoubi","meaning_id":"hari Rabu"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','木',null,'pohon / kayu',null,'{"sort_order":19,"category":"Alam","onyomi":["モク","ボク"],"kunyomi":["き"],"stroke_count":4,"examples":[{"word":"木","reading":"き","romaji":"ki","meaning_id":"pohon / kayu"},{"word":"木曜日","reading":"もくようび","romaji":"mokuyoubi","meaning_id":"hari Kamis"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','金',null,'emas / uang',null,'{"sort_order":20,"category":"Kehidupan","onyomi":["キン"],"kunyomi":["かね"],"stroke_count":8,"examples":[{"word":"お金","reading":"おかね","romaji":"okane","meaning_id":"uang"},{"word":"金曜日","reading":"きんようび","romaji":"kinyoubi","meaning_id":"hari Jumat"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','土',null,'tanah',null,'{"sort_order":21,"category":"Alam","onyomi":["ド","ト"],"kunyomi":["つち"],"stroke_count":3,"examples":[{"word":"土","reading":"つち","romaji":"tsuchi","meaning_id":"tanah"},{"word":"土曜日","reading":"どようび","romaji":"doyoubi","meaning_id":"hari Sabtu"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','年',null,'tahun',null,'{"sort_order":22,"category":"Waktu","onyomi":["ネン"],"kunyomi":["とし"],"stroke_count":6,"examples":[{"word":"今年","reading":"ことし","romaji":"kotoshi","meaning_id":"tahun ini"},{"word":"来年","reading":"らいねん","romaji":"rainen","meaning_id":"tahun depan"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','時',null,'waktu / jam',null,'{"sort_order":23,"category":"Waktu","onyomi":["ジ"],"kunyomi":["とき"],"stroke_count":10,"examples":[{"word":"一時","reading":"いちじ","romaji":"ichiji","meaning_id":"jam satu"},{"word":"時間","reading":"じかん","romaji":"jikan","meaning_id":"waktu / durasi"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','分',null,'menit / bagian / memahami',null,'{"sort_order":24,"category":"Waktu","onyomi":["ブン","フン","プン"],"kunyomi":["わ.かる","わ.ける"],"stroke_count":4,"examples":[{"word":"五分","reading":"ごふん","romaji":"gofun","meaning_id":"lima menit"},{"word":"分かる","reading":"わかる","romaji":"wakaru","meaning_id":"mengerti / memahami"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','半',null,'setengah',null,'{"sort_order":25,"category":"Waktu","onyomi":["ハン"],"kunyomi":[],"stroke_count":5,"examples":[{"word":"一時半","reading":"いちじはん","romaji":"ichiji han","meaning_id":"jam setengah dua / 1:30"},{"word":"半分","reading":"はんぶん","romaji":"hanbun","meaning_id":"setengah / separuh"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','今',null,'sekarang',null,'{"sort_order":26,"category":"Waktu","onyomi":["コン","キン"],"kunyomi":["いま"],"stroke_count":4,"examples":[{"word":"今","reading":"いま","romaji":"ima","meaning_id":"sekarang"},{"word":"今月","reading":"こんげつ","romaji":"kongetsu","meaning_id":"bulan ini"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','午',null,'siang / tengah hari',null,'{"sort_order":27,"category":"Waktu","onyomi":["ゴ"],"kunyomi":[],"stroke_count":4,"examples":[{"word":"午前","reading":"ごぜん","romaji":"gozen","meaning_id":"sebelum tengah hari / AM"},{"word":"午後","reading":"ごご","romaji":"gogo","meaning_id":"setelah tengah hari / PM"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','前',null,'depan / sebelum',null,'{"sort_order":28,"category":"Waktu","onyomi":["ゼン"],"kunyomi":["まえ"],"stroke_count":9,"examples":[{"word":"前","reading":"まえ","romaji":"mae","meaning_id":"depan / sebelumnya"},{"word":"午前","reading":"ごぜん","romaji":"gozen","meaning_id":"sebelum tengah hari / AM"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','後',null,'belakang / setelah',null,'{"sort_order":29,"category":"Waktu","onyomi":["ゴ","コウ"],"kunyomi":["あと","うし.ろ"],"stroke_count":9,"examples":[{"word":"後で","reading":"あとで","romaji":"atode","meaning_id":"nanti / setelah itu"},{"word":"午後","reading":"ごご","romaji":"gogo","meaning_id":"setelah tengah hari / PM"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','毎',null,'setiap',null,'{"sort_order":30,"category":"Waktu","onyomi":["マイ"],"kunyomi":[],"stroke_count":6,"examples":[{"word":"毎日","reading":"まいにち","romaji":"mainichi","meaning_id":"setiap hari"},{"word":"毎週","reading":"まいしゅう","romaji":"maishuu","meaning_id":"setiap minggu"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','人',null,'orang',null,'{"sort_order":31,"category":"Orang","onyomi":["ジン","ニン"],"kunyomi":["ひと"],"stroke_count":2,"examples":[{"word":"人","reading":"ひと","romaji":"hito","meaning_id":"orang"},{"word":"日本人","reading":"にほんじん","romaji":"nihonjin","meaning_id":"orang Jepang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','子',null,'anak',null,'{"sort_order":32,"category":"Orang","onyomi":["シ"],"kunyomi":["こ"],"stroke_count":3,"examples":[{"word":"子ども","reading":"こども","romaji":"kodomo","meaning_id":"anak"},{"word":"女の子","reading":"おんなのこ","romaji":"onnanoko","meaning_id":"anak perempuan"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','女',null,'perempuan',null,'{"sort_order":33,"category":"Orang","onyomi":["ジョ"],"kunyomi":["おんな"],"stroke_count":3,"examples":[{"word":"女の人","reading":"おんなのひと","romaji":"onnanohito","meaning_id":"perempuan / wanita"},{"word":"女の子","reading":"おんなのこ","romaji":"onnanoko","meaning_id":"anak perempuan"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','男',null,'laki-laki',null,'{"sort_order":34,"category":"Orang","onyomi":["ダン","ナン"],"kunyomi":["おとこ"],"stroke_count":7,"examples":[{"word":"男の人","reading":"おとこのひと","romaji":"otokonohito","meaning_id":"laki-laki / pria"},{"word":"男の子","reading":"おとこのこ","romaji":"otokonoko","meaning_id":"anak laki-laki"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','父',null,'ayah',null,'{"sort_order":35,"category":"Orang","onyomi":["フ"],"kunyomi":["ちち"],"stroke_count":4,"examples":[{"word":"父","reading":"ちち","romaji":"chichi","meaning_id":"ayah (sendiri)"},{"word":"お父さん","reading":"おとうさん","romaji":"otousan","meaning_id":"ayah / bapak"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','母',null,'ibu',null,'{"sort_order":36,"category":"Orang","onyomi":["ボ"],"kunyomi":["はは"],"stroke_count":5,"examples":[{"word":"母","reading":"はは","romaji":"haha","meaning_id":"ibu (sendiri)"},{"word":"お母さん","reading":"おかあさん","romaji":"okaasan","meaning_id":"ibu"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','友',null,'teman',null,'{"sort_order":37,"category":"Orang","onyomi":["ユウ"],"kunyomi":["とも"],"stroke_count":4,"examples":[{"word":"友だち","reading":"ともだち","romaji":"tomodachi","meaning_id":"teman"},{"word":"友人","reading":"ゆうじん","romaji":"yuujin","meaning_id":"teman / sahabat"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','先',null,'depan / lebih dahulu',null,'{"sort_order":38,"category":"Orang","onyomi":["セン"],"kunyomi":["さき"],"stroke_count":6,"examples":[{"word":"先生","reading":"せんせい","romaji":"sensei","meaning_id":"guru / pengajar"},{"word":"先月","reading":"せんげつ","romaji":"sengetsu","meaning_id":"bulan lalu"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','生',null,'hidup / lahir / mentah',null,'{"sort_order":39,"category":"Orang","onyomi":["セイ","ショウ"],"kunyomi":["い.きる","う.まれる","なま"],"stroke_count":5,"examples":[{"word":"学生","reading":"がくせい","romaji":"gakusei","meaning_id":"siswa / mahasiswa"},{"word":"生まれる","reading":"うまれる","romaji":"umareru","meaning_id":"lahir"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','名',null,'nama',null,'{"sort_order":40,"category":"Orang","onyomi":["メイ","ミョウ"],"kunyomi":["な"],"stroke_count":6,"examples":[{"word":"名前","reading":"なまえ","romaji":"namae","meaning_id":"nama"},{"word":"名字","reading":"みょうじ","romaji":"myouji","meaning_id":"nama keluarga / marga"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','山',null,'gunung',null,'{"sort_order":41,"category":"Alam","onyomi":["サン"],"kunyomi":["やま"],"stroke_count":3,"examples":[{"word":"山","reading":"やま","romaji":"yama","meaning_id":"gunung"},{"word":"富士山","reading":"ふじさん","romaji":"fujisan","meaning_id":"Gunung Fuji"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','川',null,'sungai',null,'{"sort_order":42,"category":"Alam","onyomi":["セン"],"kunyomi":["かわ"],"stroke_count":3,"examples":[{"word":"川","reading":"かわ","romaji":"kawa","meaning_id":"sungai"},{"word":"小川","reading":"おがわ","romaji":"ogawa","meaning_id":"sungai kecil / aliran kecil"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','天',null,'langit / surga',null,'{"sort_order":43,"category":"Alam","onyomi":["テン"],"kunyomi":[],"stroke_count":4,"examples":[{"word":"天気","reading":"てんき","romaji":"tenki","meaning_id":"cuaca"},{"word":"天国","reading":"てんごく","romaji":"tengoku","meaning_id":"surga"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','気',null,'perasaan / energi / suasana',null,'{"sort_order":44,"category":"Alam","onyomi":["キ","ケ"],"kunyomi":[],"stroke_count":6,"examples":[{"word":"元気","reading":"げんき","romaji":"genki","meaning_id":"sehat / bersemangat"},{"word":"天気","reading":"てんき","romaji":"tenki","meaning_id":"cuaca"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','雨',null,'hujan',null,'{"sort_order":45,"category":"Alam","onyomi":["ウ"],"kunyomi":["あめ","あま-"],"stroke_count":8,"examples":[{"word":"雨","reading":"あめ","romaji":"ame","meaning_id":"hujan"},{"word":"大雨","reading":"おおあめ","romaji":"ooame","meaning_id":"hujan lebat"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','電',null,'listrik',null,'{"sort_order":46,"category":"Kehidupan","onyomi":["デン"],"kunyomi":[],"stroke_count":13,"examples":[{"word":"電話","reading":"でんわ","romaji":"denwa","meaning_id":"telepon"},{"word":"電車","reading":"でんしゃ","romaji":"densha","meaning_id":"kereta listrik"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','学',null,'belajar / ilmu',null,'{"sort_order":47,"category":"Sekolah","onyomi":["ガク"],"kunyomi":["まな.ぶ"],"stroke_count":8,"examples":[{"word":"学生","reading":"がくせい","romaji":"gakusei","meaning_id":"siswa / mahasiswa"},{"word":"学校","reading":"がっこう","romaji":"gakkou","meaning_id":"sekolah"},{"word":"大学","reading":"だいがく","romaji":"daigaku","meaning_id":"universitas"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','校',null,'sekolah',null,'{"sort_order":48,"category":"Sekolah","onyomi":["コウ"],"kunyomi":[],"stroke_count":10,"examples":[{"word":"学校","reading":"がっこう","romaji":"gakkou","meaning_id":"sekolah"},{"word":"高校","reading":"こうこう","romaji":"koukou","meaning_id":"sekolah menengah atas"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','本',null,'buku / asal / utama',null,'{"sort_order":49,"category":"Sekolah","onyomi":["ホン"],"kunyomi":["もと"],"stroke_count":5,"examples":[{"word":"本","reading":"ほん","romaji":"hon","meaning_id":"buku"},{"word":"日本","reading":"にほん","romaji":"nihon","meaning_id":"Jepang"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','語',null,'bahasa / kata',null,'{"sort_order":50,"category":"Bahasa","onyomi":["ゴ"],"kunyomi":[],"stroke_count":14,"examples":[{"word":"日本語","reading":"にほんご","romaji":"nihongo","meaning_id":"bahasa Jepang"},{"word":"英語","reading":"えいご","romaji":"eigo","meaning_id":"bahasa Inggris"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','文',null,'kalimat / tulisan',null,'{"sort_order":51,"category":"Bahasa","onyomi":["ブン","モン"],"kunyomi":[],"stroke_count":4,"examples":[{"word":"文","reading":"ぶん","romaji":"bun","meaning_id":"kalimat / tulisan"},{"word":"作文","reading":"さくぶん","romaji":"sakubun","meaning_id":"karangan / komposisi"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','字',null,'huruf / karakter',null,'{"sort_order":52,"category":"Bahasa","onyomi":["ジ"],"kunyomi":[],"stroke_count":6,"examples":[{"word":"漢字","reading":"かんじ","romaji":"kanji","meaning_id":"huruf Kanji"},{"word":"文字","reading":"もじ","romaji":"moji","meaning_id":"huruf / karakter"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','何',null,'apa',null,'{"sort_order":53,"category":"Bahasa","onyomi":[],"kunyomi":["なに","なん"],"stroke_count":7,"examples":[{"word":"何","reading":"なに","romaji":"nani","meaning_id":"apa"},{"word":"何時","reading":"なんじ","romaji":"nanji","meaning_id":"jam berapa"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','上',null,'atas / naik',null,'{"sort_order":54,"category":"Posisi","onyomi":["ジョウ"],"kunyomi":["うえ","あ.がる","あ.げる"],"stroke_count":3,"examples":[{"word":"上","reading":"うえ","romaji":"ue","meaning_id":"atas"},{"word":"上手","reading":"じょうず","romaji":"jouzu","meaning_id":"pandai / mahir"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','下',null,'bawah / turun',null,'{"sort_order":55,"category":"Posisi","onyomi":["カ","ゲ"],"kunyomi":["した","くだ.る","さ.がる","さ.げる"],"stroke_count":3,"examples":[{"word":"下","reading":"した","romaji":"shita","meaning_id":"bawah"},{"word":"地下","reading":"ちか","romaji":"chika","meaning_id":"bawah tanah"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','中',null,'dalam / tengah',null,'{"sort_order":56,"category":"Posisi","onyomi":["チュウ"],"kunyomi":["なか"],"stroke_count":4,"examples":[{"word":"中","reading":"なか","romaji":"naka","meaning_id":"dalam / tengah"},{"word":"中国","reading":"ちゅうごく","romaji":"chuugoku","meaning_id":"Tiongkok / China"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','外',null,'luar',null,'{"sort_order":57,"category":"Posisi","onyomi":["ガイ","ゲ"],"kunyomi":["そと","ほか"],"stroke_count":5,"examples":[{"word":"外","reading":"そと","romaji":"soto","meaning_id":"luar"},{"word":"外国","reading":"がいこく","romaji":"gaikoku","meaning_id":"negara asing / luar negeri"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','左',null,'kiri',null,'{"sort_order":58,"category":"Posisi","onyomi":["サ"],"kunyomi":["ひだり"],"stroke_count":5,"examples":[{"word":"左","reading":"ひだり","romaji":"hidari","meaning_id":"kiri"},{"word":"左手","reading":"ひだりて","romaji":"hidarite","meaning_id":"tangan kiri"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','右',null,'kanan',null,'{"sort_order":59,"category":"Posisi","onyomi":["ウ","ユウ"],"kunyomi":["みぎ"],"stroke_count":5,"examples":[{"word":"右","reading":"みぎ","romaji":"migi","meaning_id":"kanan"},{"word":"右手","reading":"みぎて","romaji":"migite","meaning_id":"tangan kanan"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','東',null,'timur',null,'{"sort_order":60,"category":"Posisi","onyomi":["トウ"],"kunyomi":["ひがし"],"stroke_count":8,"examples":[{"word":"東","reading":"ひがし","romaji":"higashi","meaning_id":"timur"},{"word":"東京","reading":"とうきょう","romaji":"toukyou","meaning_id":"Tokyo"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','西',null,'barat',null,'{"sort_order":61,"category":"Posisi","onyomi":["セイ","サイ"],"kunyomi":["にし"],"stroke_count":6,"examples":[{"word":"西","reading":"にし","romaji":"nishi","meaning_id":"barat"},{"word":"西口","reading":"にしぐち","romaji":"nishiguchi","meaning_id":"pintu keluar barat"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','南',null,'selatan',null,'{"sort_order":62,"category":"Posisi","onyomi":["ナン"],"kunyomi":["みなみ"],"stroke_count":9,"examples":[{"word":"南","reading":"みなみ","romaji":"minami","meaning_id":"selatan"},{"word":"南口","reading":"みなみぐち","romaji":"minamiguchi","meaning_id":"pintu keluar selatan"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','北',null,'utara',null,'{"sort_order":63,"category":"Posisi","onyomi":["ホク"],"kunyomi":["きた"],"stroke_count":5,"examples":[{"word":"北","reading":"きた","romaji":"kita","meaning_id":"utara"},{"word":"北口","reading":"きたぐち","romaji":"kitaguchi","meaning_id":"pintu keluar utara"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','口',null,'mulut / pintu masuk-keluar',null,'{"sort_order":64,"category":"Tubuh","onyomi":["コウ","ク"],"kunyomi":["くち"],"stroke_count":3,"examples":[{"word":"口","reading":"くち","romaji":"kuchi","meaning_id":"mulut"},{"word":"入口","reading":"いりぐち","romaji":"iriguchi","meaning_id":"pintu masuk"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','目',null,'mata',null,'{"sort_order":65,"category":"Tubuh","onyomi":["モク","ボク"],"kunyomi":["め"],"stroke_count":5,"examples":[{"word":"目","reading":"め","romaji":"me","meaning_id":"mata"},{"word":"目薬","reading":"めぐすり","romaji":"megusuri","meaning_id":"obat tetes mata"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','耳',null,'telinga',null,'{"sort_order":66,"category":"Tubuh","onyomi":[],"kunyomi":["みみ"],"stroke_count":6,"examples":[{"word":"耳","reading":"みみ","romaji":"mimi","meaning_id":"telinga"},{"word":"耳かき","reading":"みみかき","romaji":"mimikaki","meaning_id":"alat pembersih telinga"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','手',null,'tangan',null,'{"sort_order":67,"category":"Tubuh","onyomi":["シュ"],"kunyomi":["て"],"stroke_count":4,"examples":[{"word":"手","reading":"て","romaji":"te","meaning_id":"tangan"},{"word":"上手","reading":"じょうず","romaji":"jouzu","meaning_id":"pandai / mahir"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','足',null,'kaki / cukup',null,'{"sort_order":68,"category":"Tubuh","onyomi":["ソク"],"kunyomi":["あし","た.りる"],"stroke_count":7,"examples":[{"word":"足","reading":"あし","romaji":"ashi","meaning_id":"kaki"},{"word":"足りる","reading":"たりる","romaji":"tariru","meaning_id":"cukup"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','大',null,'besar',null,'{"sort_order":69,"category":"Sifat","onyomi":["ダイ","タイ"],"kunyomi":["おお.きい"],"stroke_count":3,"examples":[{"word":"大きい","reading":"おおきい","romaji":"ookii","meaning_id":"besar"},{"word":"大学","reading":"だいがく","romaji":"daigaku","meaning_id":"universitas"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','小',null,'kecil',null,'{"sort_order":70,"category":"Sifat","onyomi":["ショウ"],"kunyomi":["ちい.さい","こ-"],"stroke_count":3,"examples":[{"word":"小さい","reading":"ちいさい","romaji":"chiisai","meaning_id":"kecil"},{"word":"小学校","reading":"しょうがっこう","romaji":"shougakkou","meaning_id":"sekolah dasar"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','長',null,'panjang / kepala / pemimpin',null,'{"sort_order":71,"category":"Sifat","onyomi":["チョウ"],"kunyomi":["なが.い"],"stroke_count":8,"examples":[{"word":"長い","reading":"ながい","romaji":"nagai","meaning_id":"panjang"},{"word":"校長","reading":"こうちょう","romaji":"kouchou","meaning_id":"kepala sekolah"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','高',null,'tinggi / mahal',null,'{"sort_order":72,"category":"Sifat","onyomi":["コウ"],"kunyomi":["たか.い"],"stroke_count":10,"examples":[{"word":"高い","reading":"たかい","romaji":"takai","meaning_id":"tinggi / mahal"},{"word":"高校","reading":"こうこう","romaji":"koukou","meaning_id":"sekolah menengah atas"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','安',null,'murah / aman',null,'{"sort_order":73,"category":"Sifat","onyomi":["アン"],"kunyomi":["やす.い"],"stroke_count":6,"examples":[{"word":"安い","reading":"やすい","romaji":"yasui","meaning_id":"murah"},{"word":"安心","reading":"あんしん","romaji":"anshin","meaning_id":"rasa aman / lega"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','新',null,'baru',null,'{"sort_order":74,"category":"Sifat","onyomi":["シン"],"kunyomi":["あたら.しい","あら.た"],"stroke_count":13,"examples":[{"word":"新しい","reading":"あたらしい","romaji":"atarashii","meaning_id":"baru"},{"word":"新聞","reading":"しんぶん","romaji":"shinbun","meaning_id":"surat kabar"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','古',null,'lama / tua',null,'{"sort_order":75,"category":"Sifat","onyomi":["コ"],"kunyomi":["ふる.い"],"stroke_count":5,"examples":[{"word":"古い","reading":"ふるい","romaji":"furui","meaning_id":"lama / tua"},{"word":"中古","reading":"ちゅうこ","romaji":"chuuko","meaning_id":"barang bekas"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','多',null,'banyak',null,'{"sort_order":76,"category":"Sifat","onyomi":["タ"],"kunyomi":["おお.い"],"stroke_count":6,"examples":[{"word":"多い","reading":"おおい","romaji":"ooi","meaning_id":"banyak"},{"word":"多分","reading":"たぶん","romaji":"tabun","meaning_id":"mungkin / barangkali"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','少',null,'sedikit',null,'{"sort_order":77,"category":"Sifat","onyomi":["ショウ"],"kunyomi":["すく.ない","すこ.し"],"stroke_count":4,"examples":[{"word":"少ない","reading":"すくない","romaji":"sukunai","meaning_id":"sedikit / tidak banyak"},{"word":"少し","reading":"すこし","romaji":"sukoshi","meaning_id":"sedikit"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','行',null,'pergi / melakukan',null,'{"sort_order":78,"category":"Aktivitas","onyomi":["コウ"],"kunyomi":["い.く","おこな.う"],"stroke_count":6,"examples":[{"word":"行く","reading":"いく","romaji":"iku","meaning_id":"pergi"},{"word":"銀行","reading":"ぎんこう","romaji":"ginkou","meaning_id":"bank"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','来',null,'datang',null,'{"sort_order":79,"category":"Aktivitas","onyomi":["ライ"],"kunyomi":["く.る"],"stroke_count":7,"examples":[{"word":"来る","reading":"くる","romaji":"kuru","meaning_id":"datang"},{"word":"来年","reading":"らいねん","romaji":"rainen","meaning_id":"tahun depan"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','入',null,'masuk / memasukkan',null,'{"sort_order":80,"category":"Aktivitas","onyomi":["ニュウ"],"kunyomi":["はい.る","い.れる"],"stroke_count":2,"examples":[{"word":"入る","reading":"はいる","romaji":"hairu","meaning_id":"masuk"},{"word":"入口","reading":"いりぐち","romaji":"iriguchi","meaning_id":"pintu masuk"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','出',null,'keluar / mengeluarkan',null,'{"sort_order":81,"category":"Aktivitas","onyomi":["シュツ"],"kunyomi":["で.る","だ.す"],"stroke_count":5,"examples":[{"word":"出る","reading":"でる","romaji":"deru","meaning_id":"keluar"},{"word":"出口","reading":"でぐち","romaji":"deguchi","meaning_id":"pintu keluar"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','休',null,'istirahat',null,'{"sort_order":82,"category":"Aktivitas","onyomi":["キュウ"],"kunyomi":["やす.む"],"stroke_count":6,"examples":[{"word":"休む","reading":"やすむ","romaji":"yasumu","meaning_id":"istirahat / libur"},{"word":"休日","reading":"きゅうじつ","romaji":"kyuujitsu","meaning_id":"hari libur"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','見',null,'melihat',null,'{"sort_order":83,"category":"Aktivitas","onyomi":["ケン"],"kunyomi":["み.る","み.える","み.せる"],"stroke_count":7,"examples":[{"word":"見る","reading":"みる","romaji":"miru","meaning_id":"melihat"},{"word":"見せる","reading":"みせる","romaji":"miseru","meaning_id":"memperlihatkan"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','聞',null,'mendengar / bertanya',null,'{"sort_order":84,"category":"Aktivitas","onyomi":["ブン"],"kunyomi":["き.く","き.こえる"],"stroke_count":14,"examples":[{"word":"聞く","reading":"きく","romaji":"kiku","meaning_id":"mendengar / bertanya"},{"word":"新聞","reading":"しんぶん","romaji":"shinbun","meaning_id":"surat kabar"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','読',null,'membaca',null,'{"sort_order":85,"category":"Aktivitas","onyomi":["ドク"],"kunyomi":["よ.む"],"stroke_count":14,"examples":[{"word":"読む","reading":"よむ","romaji":"yomu","meaning_id":"membaca"},{"word":"読書","reading":"どくしょ","romaji":"dokusho","meaning_id":"membaca buku / kegiatan membaca"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','書',null,'menulis',null,'{"sort_order":86,"category":"Aktivitas","onyomi":["ショ"],"kunyomi":["か.く"],"stroke_count":10,"examples":[{"word":"書く","reading":"かく","romaji":"kaku","meaning_id":"menulis"},{"word":"読書","reading":"どくしょ","romaji":"dokusho","meaning_id":"membaca buku / kegiatan membaca"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','話',null,'berbicara / cerita',null,'{"sort_order":87,"category":"Aktivitas","onyomi":["ワ"],"kunyomi":["はな.す","はなし"],"stroke_count":13,"examples":[{"word":"話す","reading":"はなす","romaji":"hanasu","meaning_id":"berbicara"},{"word":"電話","reading":"でんわ","romaji":"denwa","meaning_id":"telepon"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','食',null,'makan / makanan',null,'{"sort_order":88,"category":"Aktivitas","onyomi":["ショク"],"kunyomi":["た.べる"],"stroke_count":9,"examples":[{"word":"食べる","reading":"たべる","romaji":"taberu","meaning_id":"makan"},{"word":"食事","reading":"しょくじ","romaji":"shokuji","meaning_id":"makan / hidangan"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','飲',null,'minum',null,'{"sort_order":89,"category":"Aktivitas","onyomi":["イン"],"kunyomi":["の.む"],"stroke_count":12,"examples":[{"word":"飲む","reading":"のむ","romaji":"nomu","meaning_id":"minum"},{"word":"飲み物","reading":"のみもの","romaji":"nomimono","meaning_id":"minuman"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true),
  ('kanji','N5','買',null,'membeli',null,'{"sort_order":90,"category":"Aktivitas","onyomi":["バイ"],"kunyomi":["か.う"],"stroke_count":12,"examples":[{"word":"買う","reading":"かう","romaji":"kau","meaning_id":"membeli"},{"word":"買い物","reading":"かいもの","romaji":"kaimono","meaning_id":"belanja / barang belanjaan"}],"curriculum":"KOJAC Kanji Core","dataset":"N5-v1"}'::jsonb,true)
on conflict (item_type, prompt, (coalesce(reading, '')))
do update set
  jlpt_level = excluded.jlpt_level,
  meaning_id = excluded.meaning_id,
  extra = coalesce(li.extra, '{}'::jsonb) || excluded.extra,
  is_published = excluded.is_published;

-- Validation: all 90 KOJAC N5 rows must exist as the single-kanji records used by the UI.
do $$
declare
  v_count integer;
  v_order_count integer;
  v_missing_metadata integer;
begin
  select count(*)
  into v_count
  from public.learning_items
  where item_type = 'kanji'
    and jlpt_level = 'N5'
    and reading is null
    and prompt in ('一','二','三','四','五','六','七','八','九','十','百','千','万','円','日','月','火','水','木','金','土','年','時','分','半','今','午','前','後','毎','人','子','女','男','父','母','友','先','生','名','山','川','天','気','雨','電','学','校','本','語','文','字','何','上','下','中','外','左','右','東','西','南','北','口','目','耳','手','足','大','小','長','高','安','新','古','多','少','行','来','入','出','休','見','聞','読','書','話','食','飲','買');

  if v_count <> 90 then
    raise exception 'KOJAC Kanji N5 validation failed: expected 90 rows, found %', v_count;
  end if;

  select count(distinct (extra->>'sort_order')::integer)
  into v_order_count
  from public.learning_items
  where item_type = 'kanji'
    and jlpt_level = 'N5'
    and reading is null
    and prompt in ('一','二','三','四','五','六','七','八','九','十','百','千','万','円','日','月','火','水','木','金','土','年','時','分','半','今','午','前','後','毎','人','子','女','男','父','母','友','先','生','名','山','川','天','気','雨','電','学','校','本','語','文','字','何','上','下','中','外','左','右','東','西','南','北','口','目','耳','手','足','大','小','長','高','安','新','古','多','少','行','来','入','出','休','見','聞','読','書','話','食','飲','買');

  if v_order_count <> 90 then
    raise exception 'KOJAC Kanji N5 validation failed: sort_order must be unique from 1 to 90';
  end if;

  select count(*)
  into v_missing_metadata
  from public.learning_items
  where item_type = 'kanji'
    and jlpt_level = 'N5'
    and reading is null
    and prompt in ('一','二','三','四','五','六','七','八','九','十','百','千','万','円','日','月','火','水','木','金','土','年','時','分','半','今','午','前','後','毎','人','子','女','男','父','母','友','先','生','名','山','川','天','気','雨','電','学','校','本','語','文','字','何','上','下','中','外','左','右','東','西','南','北','口','目','耳','手','足','大','小','長','高','安','新','古','多','少','行','来','入','出','休','見','聞','読','書','話','食','飲','買')
    and (
      meaning_id is null
      or coalesce(extra->>'category', '') = ''
      or jsonb_typeof(extra->'onyomi') is distinct from 'array'
      or jsonb_typeof(extra->'kunyomi') is distinct from 'array'
      or coalesce((extra->>'stroke_count')::integer, 0) <= 0
      or jsonb_typeof(extra->'examples') is distinct from 'array'
      or jsonb_array_length(extra->'examples') < 2
    );

  if v_missing_metadata <> 0 then
    raise exception 'KOJAC Kanji N5 validation failed: % row(s) have incomplete metadata', v_missing_metadata;
  end if;
end $$;
